name: chip8
version: 0.0.1
description: Implementation of a chip8 emulator
homepage: https://github.com/ReimuA/Monke8
repository: https://github.com/ReimuA/Monke8
issue_tracker: https://github.com/ReimuA/Monke8/issues

publish_to: https://pub.dev/

environment:
  sdk: ">=2.16.2 <3.0.0"

# dependencies:
#   path: ^1.8.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
dependencies:
  collection: ^1.16.0
